//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloaderClientGUI.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FloaderClientGUI.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        internal static string Baudrate {
            get {
                return ResourceManager.GetString("Baudrate", resourceCulture);
            }
        }
        
        internal static string DataBits {
            get {
                return ResourceManager.GetString("DataBits", resourceCulture);
            }
        }
        
        internal static string DeviceIdentified {
            get {
                return ResourceManager.GetString("DeviceIdentified", resourceCulture);
            }
        }
        
        internal static string GenericWrongDeviceResponseTitle {
            get {
                return ResourceManager.GetString("GenericWrongDeviceResponseTitle", resourceCulture);
            }
        }
        
        internal static string IdentificationTimeout {
            get {
                return ResourceManager.GetString("IdentificationTimeout", resourceCulture);
            }
        }
        
        internal static string IdentificationTimeoutTitle {
            get {
                return ResourceManager.GetString("IdentificationTimeoutTitle", resourceCulture);
            }
        }
        
        internal static string InterfaceAlreadyLocked {
            get {
                return ResourceManager.GetString("InterfaceAlreadyLocked", resourceCulture);
            }
        }
        
        internal static string InterfaceAlreadyUnlocked {
            get {
                return ResourceManager.GetString("InterfaceAlreadyUnlocked", resourceCulture);
            }
        }
        
        internal static string LocBtnDownload {
            get {
                return ResourceManager.GetString("LocBtnDownload", resourceCulture);
            }
        }
        
        internal static string LocBtnPoll {
            get {
                return ResourceManager.GetString("LocBtnPoll", resourceCulture);
            }
        }
        
        internal static string LocBtnReboot {
            get {
                return ResourceManager.GetString("LocBtnReboot", resourceCulture);
            }
        }
        
        internal static string LocBtnSelectPort {
            get {
                return ResourceManager.GetString("LocBtnSelectPort", resourceCulture);
            }
        }
        
        internal static string LocBtnUpload {
            get {
                return ResourceManager.GetString("LocBtnUpload", resourceCulture);
            }
        }
        
        internal static string LocButtonCancel {
            get {
                return ResourceManager.GetString("LocButtonCancel", resourceCulture);
            }
        }
        
        internal static string LocButtonOK {
            get {
                return ResourceManager.GetString("LocButtonOK", resourceCulture);
            }
        }
        
        internal static string LocButtonRefresh {
            get {
                return ResourceManager.GetString("LocButtonRefresh", resourceCulture);
            }
        }
        
        internal static string LocButtonReset {
            get {
                return ResourceManager.GetString("LocButtonReset", resourceCulture);
            }
        }
        
        internal static string LocCommonEllipsis {
            get {
                return ResourceManager.GetString("LocCommonEllipsis", resourceCulture);
            }
        }
        
        internal static string LocGroupboxAbout {
            get {
                return ResourceManager.GetString("LocGroupboxAbout", resourceCulture);
            }
        }
        
        internal static string LocGroupboxAdvancedOptions {
            get {
                return ResourceManager.GetString("LocGroupboxAdvancedOptions", resourceCulture);
            }
        }
        
        internal static string LocGroupboxConsole {
            get {
                return ResourceManager.GetString("LocGroupboxConsole", resourceCulture);
            }
        }
        
        internal static string LocGroupboxDevice {
            get {
                return ResourceManager.GetString("LocGroupboxDevice", resourceCulture);
            }
        }
        
        internal static string LocGroupboxDownload {
            get {
                return ResourceManager.GetString("LocGroupboxDownload", resourceCulture);
            }
        }
        
        internal static string LocGroupboxPort {
            get {
                return ResourceManager.GetString("LocGroupboxPort", resourceCulture);
            }
        }
        
        internal static string LocGroupboxPortsList {
            get {
                return ResourceManager.GetString("LocGroupboxPortsList", resourceCulture);
            }
        }
        
        internal static string LocGroupboxProgress {
            get {
                return ResourceManager.GetString("LocGroupboxProgress", resourceCulture);
            }
        }
        
        internal static string LocGroupboxUpload {
            get {
                return ResourceManager.GetString("LocGroupboxUpload", resourceCulture);
            }
        }
        
        internal static string LocTextAbout {
            get {
                return ResourceManager.GetString("LocTextAbout", resourceCulture);
            }
        }
        
        internal static string LocTextAgpl {
            get {
                return ResourceManager.GetString("LocTextAgpl", resourceCulture);
            }
        }
        
        internal static string LocTextAuthors1 {
            get {
                return ResourceManager.GetString("LocTextAuthors1", resourceCulture);
            }
        }
        
        internal static string LocTextAuthors2 {
            get {
                return ResourceManager.GetString("LocTextAuthors2", resourceCulture);
            }
        }
        
        internal static string LocTextBackups {
            get {
                return ResourceManager.GetString("LocTextBackups", resourceCulture);
            }
        }
        
        internal static string LocTextBaudrate {
            get {
                return ResourceManager.GetString("LocTextBaudrate", resourceCulture);
            }
        }
        
        internal static string LocTextDataBits {
            get {
                return ResourceManager.GetString("LocTextDataBits", resourceCulture);
            }
        }
        
        internal static string LocTextEeprom {
            get {
                return ResourceManager.GetString("LocTextEeprom", resourceCulture);
            }
        }
        
        internal static string LocTextEmail {
            get {
                return ResourceManager.GetString("LocTextEmail", resourceCulture);
            }
        }
        
        internal static string LocTextFlash {
            get {
                return ResourceManager.GetString("LocTextFlash", resourceCulture);
            }
        }
        
        internal static string LocTextLicense {
            get {
                return ResourceManager.GetString("LocTextLicense", resourceCulture);
            }
        }
        
        internal static string LocTextLicenseText {
            get {
                return ResourceManager.GetString("LocTextLicenseText", resourceCulture);
            }
        }
        
        internal static string LocTextModel {
            get {
                return ResourceManager.GetString("LocTextModel", resourceCulture);
            }
        }
        
        internal static string LocTextOperation {
            get {
                return ResourceManager.GetString("LocTextOperation", resourceCulture);
            }
        }
        
        internal static string LocTextOrLaterVersion {
            get {
                return ResourceManager.GetString("LocTextOrLaterVersion", resourceCulture);
            }
        }
        
        internal static string LocTextOverrideDefaults {
            get {
                return ResourceManager.GetString("LocTextOverrideDefaults", resourceCulture);
            }
        }
        
        internal static string LocTextParity {
            get {
                return ResourceManager.GetString("LocTextParity", resourceCulture);
            }
        }
        
        internal static string LocTextPort {
            get {
                return ResourceManager.GetString("LocTextPort", resourceCulture);
            }
        }
        
        internal static string LocTextSelectBackupsDirectory {
            get {
                return ResourceManager.GetString("LocTextSelectBackupsDirectory", resourceCulture);
            }
        }
        
        internal static string LocTextSelectEepromHexFile {
            get {
                return ResourceManager.GetString("LocTextSelectEepromHexFile", resourceCulture);
            }
        }
        
        internal static string LocTextSelectFlashHexFile {
            get {
                return ResourceManager.GetString("LocTextSelectFlashHexFile", resourceCulture);
            }
        }
        
        internal static string LocTextSerial {
            get {
                return ResourceManager.GetString("LocTextSerial", resourceCulture);
            }
        }
        
        internal static string LocTextSoftwareDescription {
            get {
                return ResourceManager.GetString("LocTextSoftwareDescription", resourceCulture);
            }
        }
        
        internal static string LocTextSources {
            get {
                return ResourceManager.GetString("LocTextSources", resourceCulture);
            }
        }
        
        internal static string LocTextStopBits {
            get {
                return ResourceManager.GetString("LocTextStopBits", resourceCulture);
            }
        }
        
        internal static string LocTextVendor {
            get {
                return ResourceManager.GetString("LocTextVendor", resourceCulture);
            }
        }
        
        internal static string LocTextWriteEepromIntoThisFile {
            get {
                return ResourceManager.GetString("LocTextWriteEepromIntoThisFile", resourceCulture);
            }
        }
        
        internal static string LocTextWriteFlashIntoThisFile {
            get {
                return ResourceManager.GetString("LocTextWriteFlashIntoThisFile", resourceCulture);
            }
        }
        
        internal static string LoggerError {
            get {
                return ResourceManager.GetString("LoggerError", resourceCulture);
            }
        }
        
        internal static string LoggerInfo {
            get {
                return ResourceManager.GetString("LoggerInfo", resourceCulture);
            }
        }
        
        internal static string LoggerWarning {
            get {
                return ResourceManager.GetString("LoggerWarning", resourceCulture);
            }
        }
        
        internal static string ModelNameInfo {
            get {
                return ResourceManager.GetString("ModelNameInfo", resourceCulture);
            }
        }
        
        internal static string ModelNotFound {
            get {
                return ResourceManager.GetString("ModelNotFound", resourceCulture);
            }
        }
        
        internal static string ModelNotFoundTitle {
            get {
                return ResourceManager.GetString("ModelNotFoundTitle", resourceCulture);
            }
        }
        
        internal static string NoOperationInProgress {
            get {
                return ResourceManager.GetString("NoOperationInProgress", resourceCulture);
            }
        }
        
        internal static string NotReady {
            get {
                return ResourceManager.GetString("NotReady", resourceCulture);
            }
        }
        
        internal static string Parity {
            get {
                return ResourceManager.GetString("Parity", resourceCulture);
            }
        }
        
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        internal static string PortNotSelected {
            get {
                return ResourceManager.GetString("PortNotSelected", resourceCulture);
            }
        }
        
        internal static string PortSettings {
            get {
                return ResourceManager.GetString("PortSettings", resourceCulture);
            }
        }
        
        internal static string QueryingDeviceName {
            get {
                return ResourceManager.GetString("QueryingDeviceName", resourceCulture);
            }
        }
        
        internal static string QueryingVendorData {
            get {
                return ResourceManager.GetString("QueryingVendorData", resourceCulture);
            }
        }
        
        internal static string StopBits {
            get {
                return ResourceManager.GetString("StopBits", resourceCulture);
            }
        }
        
        internal static string UnableToProceed {
            get {
                return ResourceManager.GetString("UnableToProceed", resourceCulture);
            }
        }
        
        internal static string UnexpectedExceptionMessage {
            get {
                return ResourceManager.GetString("UnexpectedExceptionMessage", resourceCulture);
            }
        }
        
        internal static string UnexpectedExceptionTitle {
            get {
                return ResourceManager.GetString("UnexpectedExceptionTitle", resourceCulture);
            }
        }
        
        internal static string UnexpectedIdentificationResponse {
            get {
                return ResourceManager.GetString("UnexpectedIdentificationResponse", resourceCulture);
            }
        }
        
        internal static string UnsuccessfullReboot {
            get {
                return ResourceManager.GetString("UnsuccessfullReboot", resourceCulture);
            }
        }
        
        internal static string UnsuccessfullRebootTitle {
            get {
                return ResourceManager.GetString("UnsuccessfullRebootTitle", resourceCulture);
            }
        }
        
        internal static string UnsupportedBootloaderProtocolVersion {
            get {
                return ResourceManager.GetString("UnsupportedBootloaderProtocolVersion", resourceCulture);
            }
        }
        
        internal static string UnsupportedBootloaderProtocolVersionTitle {
            get {
                return ResourceManager.GetString("UnsupportedBootloaderProtocolVersionTitle", resourceCulture);
            }
        }
        
        internal static string UnsupportedOS {
            get {
                return ResourceManager.GetString("UnsupportedOS", resourceCulture);
            }
        }
        
        internal static string VendorNameInfo {
            get {
                return ResourceManager.GetString("VendorNameInfo", resourceCulture);
            }
        }
        
        internal static string VendorNotFound {
            get {
                return ResourceManager.GetString("VendorNotFound", resourceCulture);
            }
        }
        
        internal static string VendorNotFoundTitle {
            get {
                return ResourceManager.GetString("VendorNotFoundTitle", resourceCulture);
            }
        }
        
        internal static string IncorrectEepromFileTitle {
            get {
                return ResourceManager.GetString("IncorrectEepromFileTitle", resourceCulture);
            }
        }
        
        internal static string IncorrectEepromFile {
            get {
                return ResourceManager.GetString("IncorrectEepromFile", resourceCulture);
            }
        }
    }
}
