//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloaderClientGUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FloaderClientGUI.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fossa&apos;s AVR loader.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0.2 (24 Oct 2020).
        /// </summary>
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baudrate: {0}.
        /// </summary>
        internal static string Baudrate {
            get {
                return ResourceManager.GetString("Baudrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data bits: {0}.
        /// </summary>
        internal static string DataBits {
            get {
                return ResourceManager.GetString("DataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device identified:
        ///Version: {0},
        ///Vendor ID: {1},
        ///Model ID: {2},
        ///Serial number: {3}..
        /// </summary>
        internal static string DeviceIdentified {
            get {
                return ResourceManager.GetString("DeviceIdentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong device response.
        /// </summary>
        internal static string GenericWrongDeviceResponseTitle {
            get {
                return ResourceManager.GetString("GenericWrongDeviceResponseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to identify device timed out. Check port and device state - it must be in bootloader mode..
        /// </summary>
        internal static string IdentificationTimeout {
            get {
                return ResourceManager.GetString("IdentificationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification timeout.
        /// </summary>
        internal static string IdentificationTimeoutTitle {
            get {
                return ResourceManager.GetString("IdentificationTimeoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface already locked..
        /// </summary>
        internal static string InterfaceAlreadyLocked {
            get {
                return ResourceManager.GetString("InterfaceAlreadyLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface already unlocked..
        /// </summary>
        internal static string InterfaceAlreadyUnlocked {
            get {
                return ResourceManager.GetString("InterfaceAlreadyUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string LocBtnDownload {
            get {
                return ResourceManager.GetString("LocBtnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll.
        /// </summary>
        internal static string LocBtnPoll {
            get {
                return ResourceManager.GetString("LocBtnPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        internal static string LocBtnReboot {
            get {
                return ResourceManager.GetString("LocBtnReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select port.
        /// </summary>
        internal static string LocBtnSelectPort {
            get {
                return ResourceManager.GetString("LocBtnSelectPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string LocBtnUpload {
            get {
                return ResourceManager.GetString("LocBtnUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string LocCommonEllipsis {
            get {
                return ResourceManager.GetString("LocCommonEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About:.
        /// </summary>
        internal static string LocGroupboxAbout {
            get {
                return ResourceManager.GetString("LocGroupboxAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console:.
        /// </summary>
        internal static string LocGroupboxConsole {
            get {
                return ResourceManager.GetString("LocGroupboxConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device:.
        /// </summary>
        internal static string LocGroupboxDevice {
            get {
                return ResourceManager.GetString("LocGroupboxDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download:.
        /// </summary>
        internal static string LocGroupboxDownload {
            get {
                return ResourceManager.GetString("LocGroupboxDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string LocGroupboxPort {
            get {
                return ResourceManager.GetString("LocGroupboxPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress:.
        /// </summary>
        internal static string LocGroupboxProgress {
            get {
                return ResourceManager.GetString("LocGroupboxProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload:.
        /// </summary>
        internal static string LocGroupboxUpload {
            get {
                return ResourceManager.GetString("LocGroupboxUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string LocTextAbout {
            get {
                return ResourceManager.GetString("LocTextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups:.
        /// </summary>
        internal static string LocTextBackups {
            get {
                return ResourceManager.GetString("LocTextBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEPROM:.
        /// </summary>
        internal static string LocTextEeprom {
            get {
                return ResourceManager.GetString("LocTextEeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASH:.
        /// </summary>
        internal static string LocTextFlash {
            get {
                return ResourceManager.GetString("LocTextFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model:.
        /// </summary>
        internal static string LocTextModel {
            get {
                return ResourceManager.GetString("LocTextModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation:.
        /// </summary>
        internal static string LocTextOperation {
            get {
                return ResourceManager.GetString("LocTextOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string LocTextPort {
            get {
                return ResourceManager.GetString("LocTextPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select backups directory.
        /// </summary>
        internal static string LocTextSelectBackupsDirectory {
            get {
                return ResourceManager.GetString("LocTextSelectBackupsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select EEPROM HEX file.
        /// </summary>
        internal static string LocTextSelectEepromHexFile {
            get {
                return ResourceManager.GetString("LocTextSelectEepromHexFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select FLASH HEX file.
        /// </summary>
        internal static string LocTextSelectFlashHexFile {
            get {
                return ResourceManager.GetString("LocTextSelectFlashHexFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number:.
        /// </summary>
        internal static string LocTextSerial {
            get {
                return ResourceManager.GetString("LocTextSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor:.
        /// </summary>
        internal static string LocTextVendor {
            get {
                return ResourceManager.GetString("LocTextVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write EEPROM HEX into this file.
        /// </summary>
        internal static string LocTextWriteEepromIntoThisFile {
            get {
                return ResourceManager.GetString("LocTextWriteEepromIntoThisFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write FLASH HEX into this file.
        /// </summary>
        internal static string LocTextWriteFlashIntoThisFile {
            get {
                return ResourceManager.GetString("LocTextWriteFlashIntoThisFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Error: {1}.
        /// </summary>
        internal static string LoggerError {
            get {
                return ResourceManager.GetString("LoggerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Info: {1}.
        /// </summary>
        internal static string LoggerInfo {
            get {
                return ResourceManager.GetString("LoggerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Warning: {1}.
        /// </summary>
        internal static string LoggerWarning {
            get {
                return ResourceManager.GetString("LoggerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor ID={0}, Model ID={1}, Model name=&quot;{2}&quot;..
        /// </summary>
        internal static string ModelNameInfo {
            get {
                return ResourceManager.GetString("ModelNameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device model with Vendor ID={0} and ModelID={1} wasn&apos;t found in database..
        /// </summary>
        internal static string ModelNotFound {
            get {
                return ResourceManager.GetString("ModelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown model.
        /// </summary>
        internal static string ModelNotFoundTitle {
            get {
                return ResourceManager.GetString("ModelNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NoOperationInProgress {
            get {
                return ResourceManager.GetString("NoOperationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not ready to proceed!.
        /// </summary>
        internal static string NotReady {
            get {
                return ResourceManager.GetString("NotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity: {0}.
        /// </summary>
        internal static string Parity {
            get {
                return ResourceManager.GetString("Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port: {0}.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port not selected!.
        /// </summary>
        internal static string PortNotSelected {
            get {
                return ResourceManager.GetString("PortNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port settings:.
        /// </summary>
        internal static string PortSettings {
            get {
                return ResourceManager.GetString("PortSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying device name data for Vendor ID={0}, Model ID={1}..
        /// </summary>
        internal static string QueryingDeviceName {
            get {
                return ResourceManager.GetString("QueryingDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queriying vendor data for Vendor ID={0}..
        /// </summary>
        internal static string QueryingVendorData {
            get {
                return ResourceManager.GetString("QueryingVendorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop bits: {0}.
        /// </summary>
        internal static string StopBits {
            get {
                return ResourceManager.GetString("StopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to proceed!
        ///Please, select another device..
        /// </summary>
        internal static string UnableToProceed {
            get {
                return ResourceManager.GetString("UnableToProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device responded to identification request in unusual way, probably it&apos;s not Fossa&apos;s bootloader device.
        ///Check port and device state - it must be in bootloader mode..
        /// </summary>
        internal static string UnexpectedIdentificationResponse {
            get {
                return ResourceManager.GetString("UnexpectedIdentificationResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device didn&apos;t report reboot. Check manually did it reboot or not..
        /// </summary>
        internal static string UnsuccessfullReboot {
            get {
                return ResourceManager.GetString("UnsuccessfullReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot is unsuccessfull.
        /// </summary>
        internal static string UnsuccessfullRebootTitle {
            get {
                return ResourceManager.GetString("UnsuccessfullRebootTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootloader protocol version {0} is not supported..
        /// </summary>
        internal static string UnsupportedBootloaderProtocolVersion {
            get {
                return ResourceManager.GetString("UnsupportedBootloaderProtocolVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported protocol version.
        /// </summary>
        internal static string UnsupportedBootloaderProtocolVersionTitle {
            get {
                return ResourceManager.GetString("UnsupportedBootloaderProtocolVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported OS..
        /// </summary>
        internal static string UnsupportedOS {
            get {
                return ResourceManager.GetString("UnsupportedOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor ID={0}, Vendor name=&quot;{1}&quot;..
        /// </summary>
        internal static string VendorNameInfo {
            get {
                return ResourceManager.GetString("VendorNameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor with ID={0} wasn&apos;t found in database..
        /// </summary>
        internal static string VendorNotFound {
            get {
                return ResourceManager.GetString("VendorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown vendor.
        /// </summary>
        internal static string VendorNotFoundTitle {
            get {
                return ResourceManager.GetString("VendorNotFoundTitle", resourceCulture);
            }
        }
    }
}
