//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibFloaderClient.Implementations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibFloaderClient.Implementations.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given EEPROM file contains data for addressess outside EEPROM. Check file correctness..
        /// </summary>
        internal static string AddressOutsideEeprom {
            get {
                return ResourceManager.GetString("AddressOutsideEeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed FLASH page addresses: [0 - {0}]..
        /// </summary>
        internal static string AllowedFlashPageAddresses {
            get {
                return ResourceManager.GetString("AllowedFlashPageAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already disposed..
        /// </summary>
        internal static string AlreadyDisposed {
            get {
                return ResourceManager.GetString("AlreadyDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly {0} not found..
        /// </summary>
        internal static string AssemblyNotFound {
            get {
                return ResourceManager.GetString("AssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up....
        /// </summary>
        internal static string BackingUp {
            get {
                return ResourceManager.GetString("BackingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups directory must be specified..
        /// </summary>
        internal static string BackupsDirectoryMustBeSpecified {
            get {
                return ResourceManager.GetString("BackupsDirectoryMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed.
        /// </summary>
        internal static string DownloadCompleted {
            get {
                return ResourceManager.GetString("DownloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded. Writting to file....
        /// </summary>
        internal static string DownloadedWritingInto {
            get {
                return ResourceManager.GetString("DownloadedWritingInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading EEPROM into {0}....
        /// </summary>
        internal static string DownloadingEepromInto {
            get {
                return ResourceManager.GetString("DownloadingEepromInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading FLASH into {0}....
        /// </summary>
        internal static string DownloadingFlashInto {
            get {
                return ResourceManager.GetString("DownloadingFlashInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEPROM backup file: {0}.
        /// </summary>
        internal static string EepromBackupFile {
            get {
                return ResourceManager.GetString("EepromBackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEPROM file to download into must be specified..
        /// </summary>
        internal static string EepromFileToDownloadMustBeSpecified {
            get {
                return ResourceManager.GetString("EepromFileToDownloadMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout during EEPROM read..
        /// </summary>
        internal static string EepromReadTimeout {
            get {
                return ResourceManager.GetString("EepromReadTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEPROM size: {0} bytes.
        /// </summary>
        internal static string EepromSize {
            get {
                return ResourceManager.GetString("EepromSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected write EEPROM byte response..
        /// </summary>
        internal static string EepromWriteByteUnexpectedResponse {
            get {
                return ResourceManager.GetString("EepromWriteByteUnexpectedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected write EEPROM byte response size: {0} bytes..
        /// </summary>
        internal static string EepromWriteByteUnexpectedResponseSize {
            get {
                return ResourceManager.GetString("EepromWriteByteUnexpectedResponseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device don&apos;t accept new data after writing {0} / {1} bytes..
        /// </summary>
        internal static string EepromWriteDontAcceptData {
            get {
                return ResourceManager.GetString("EepromWriteDontAcceptData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device wants more data after writing the last byte of EEPROM..
        /// </summary>
        internal static string EepromWriteGreedyDevice {
            get {
                return ResourceManager.GetString("EepromWriteGreedyDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASH and EEPROM files must differ..
        /// </summary>
        internal static string FlashAndEepromMustDiffer {
            get {
                return ResourceManager.GetString("FlashAndEepromMustDiffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASH backup file: {0}.
        /// </summary>
        internal static string FlashBackupFile {
            get {
                return ResourceManager.GetString("FlashBackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASH file to download into must be specified..
        /// </summary>
        internal static string FlashFileToDownloadMustBeSpecified {
            get {
                return ResourceManager.GetString("FlashFileToDownloadMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least either FLASH or EEPROM files must be specified..
        /// </summary>
        internal static string FlashOrEepromMustBeSpecified {
            get {
                return ResourceManager.GetString("FlashOrEepromMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASH page size: {0} bytes.
        /// </summary>
        internal static string FlashPageSize {
            get {
                return ResourceManager.GetString("FlashPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASH page {0} verification failed..
        /// </summary>
        internal static string FlashPageVerificationFailed {
            get {
                return ResourceManager.GetString("FlashPageVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device reports failure during FLASH page {0} read..
        /// </summary>
        internal static string FlashReadFailure {
            get {
                return ResourceManager.GetString("FlashReadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout during FLASH read..
        /// </summary>
        internal static string FlashReadTimeout {
            get {
                return ResourceManager.GetString("FlashReadTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected response to FLASH page {0} read initiation..
        /// </summary>
        internal static string FlashReadUnexpectedResponse {
            get {
                return ResourceManager.GetString("FlashReadUnexpectedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected response size to FLASH page read request: {0} bytes..
        /// </summary>
        internal static string FlashReadUnexpectedResponseSize {
            get {
                return ResourceManager.GetString("FlashReadUnexpectedResponseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected response to FLASH page {0} write address check..
        /// </summary>
        internal static string FlashWriteAddressCheckUnexpectedResponse {
            get {
                return ResourceManager.GetString("FlashWriteAddressCheckUnexpectedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device reports failure during FLASH page write..
        /// </summary>
        internal static string FlashWriteFailure {
            get {
                return ResourceManager.GetString("FlashWriteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device reports incorrect FLASH page address {0} while attempt to write..
        /// </summary>
        internal static string FlashWriteIncorrectPageAddress {
            get {
                return ResourceManager.GetString("FlashWriteIncorrectPageAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout during FLASH write..
        /// </summary>
        internal static string FlashWriteTimeout {
            get {
                return ResourceManager.GetString("FlashWriteTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected response size to FLASH page write address check request: {0} bytes..
        /// </summary>
        internal static string FlashWriteUnexpectedAddressCheckResponseSize {
            get {
                return ResourceManager.GetString("FlashWriteUnexpectedAddressCheckResponseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected response size to FLASH page write request: {0} bytes..
        /// </summary>
        internal static string FlashWriteUnexpectedResponseSize {
            get {
                return ResourceManager.GetString("FlashWriteUnexpectedResponseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writeable page addresses: [0 - {0}]..
        /// </summary>
        internal static string FlashWriteWriteableAddressess {
            get {
                return ResourceManager.GetString("FlashWriteWriteableAddressess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected FLASH page data size is {0} bytes..
        /// </summary>
        internal static string FlashWriteWrongPageSize {
            get {
                return ResourceManager.GetString("FlashWriteWrongPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting version-specific data....
        /// </summary>
        internal static string GettingVersionSpecificData {
            get {
                return ResourceManager.GetString("GettingVersionSpecificData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect position..
        /// </summary>
        internal static string IncorrectPosition {
            get {
                return ResourceManager.GetString("IncorrectPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During IO {0} error happened..
        /// </summary>
        internal static string IOError {
            get {
                return ResourceManager.GetString("IOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple read timeout..
        /// </summary>
        internal static string MultipleReadTimeout {
            get {
                return ResourceManager.GetString("MultipleReadTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to use not set up Device Independent Operations Provider.
        /// </summary>
        internal static string NotSetUpDIOProvider {
            get {
                return ResourceManager.GetString("NotSetUpDIOProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even.
        /// </summary>
        internal static string ParityEven {
            get {
                return ResourceManager.GetString("ParityEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        internal static string ParityMark {
            get {
                return ResourceManager.GetString("ParityMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parity control.
        /// </summary>
        internal static string ParityNone {
            get {
                return ResourceManager.GetString("ParityNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odd.
        /// </summary>
        internal static string ParityOdd {
            get {
                return ResourceManager.GetString("ParityOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        internal static string ParitySpace {
            get {
                return ResourceManager.GetString("ParitySpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port isn&apos;t open..
        /// </summary>
        internal static string PortIsntOpen {
            get {
                return ResourceManager.GetString("PortIsntOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position is outside of the response..
        /// </summary>
        internal static string PositionIsOutsideResponse {
            get {
                return ResourceManager.GetString("PositionIsOutsideResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading EEPROM.
        /// </summary>
        internal static string ProgressOperationReadingEeprom {
            get {
                return ResourceManager.GetString("ProgressOperationReadingEeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading FLASH.
        /// </summary>
        internal static string ProgressOperationReadingFlash {
            get {
                return ResourceManager.GetString("ProgressOperationReadingFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing EEPROM.
        /// </summary>
        internal static string ProgressOperationWritingEeprom {
            get {
                return ResourceManager.GetString("ProgressOperationWritingEeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing FLASH.
        /// </summary>
        internal static string ProgressOperationWritingFlash {
            get {
                return ResourceManager.GetString("ProgressOperationWritingFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading EEPROM....
        /// </summary>
        internal static string ReadingEeprom {
            get {
                return ResourceManager.GetString("ReadingEeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading FLASH (bootloader included)....
        /// </summary>
        internal static string ReadingFlash {
            get {
                return ResourceManager.GetString("ReadingFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting reboot....
        /// </summary>
        internal static string RequestingReboot {
            get {
                return ResourceManager.GetString("RequestingReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource {0} not found..
        /// </summary>
        internal static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single read timeout..
        /// </summary>
        internal static string SingleReadTimeout {
            get {
                return ResourceManager.GetString("SingleReadTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        internal static string StopBitsOne {
            get {
                return ResourceManager.GetString("StopBitsOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One and half.
        /// </summary>
        internal static string StopBitsOnePointFive {
            get {
                return ResourceManager.GetString("StopBitsOnePointFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        internal static string StopBitsTwo {
            get {
                return ResourceManager.GetString("StopBitsTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device didn&apos;t respond in time, check did it reboot manually..
        /// </summary>
        internal static string TimeoutOnReboot {
            get {
                return ResourceManager.GetString("TimeoutOnReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total FLASH pages: {0}.
        /// </summary>
        internal static string TotalFlashPages {
            get {
                return ResourceManager.GetString("TotalFlashPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get device data for VendorId={0}, ModelId={1}.
        /// </summary>
        internal static string UnableToGetDeviceData {
            get {
                return ResourceManager.GetString("UnableToGetDeviceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device returned unknown response: {0}.
        /// </summary>
        internal static string UnknownDeviceResponceOnReboot {
            get {
                return ResourceManager.GetString("UnknownDeviceResponceOnReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported version {0}..
        /// </summary>
        internal static string UnsupportedVersion {
            get {
                return ResourceManager.GetString("UnsupportedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given FLASH file contains data for addresses in non-writeable FLASH area. Check file correctness..
        /// </summary>
        internal static string UnwriteableFlashArea {
            get {
                return ResourceManager.GetString("UnwriteableFlashArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading EEPROM....
        /// </summary>
        internal static string UploadingEeprom {
            get {
                return ResourceManager.GetString("UploadingEeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading FLASH....
        /// </summary>
        internal static string UploadingFlash {
            get {
                return ResourceManager.GetString("UploadingFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version must be 1..
        /// </summary>
        internal static string VersionMustBeOne {
            get {
                return ResourceManager.GetString("VersionMustBeOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1 detected.
        /// </summary>
        internal static string VersionOneDetected {
            get {
                return ResourceManager.GetString("VersionOneDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writeable FLASH pages: {0}.
        /// </summary>
        internal static string WriteableFlashPages {
            get {
                return ResourceManager.GetString("WriteableFlashPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write timeout..
        /// </summary>
        internal static string WriteTimeout {
            get {
                return ResourceManager.GetString("WriteTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing EEPROM....
        /// </summary>
        internal static string WritingEeprom {
            get {
                return ResourceManager.GetString("WritingEeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing FLASH (except bootloader)....
        /// </summary>
        internal static string WritingFlash {
            get {
                return ResourceManager.GetString("WritingFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data to write size must equal EEPROM size: {0} bytes..
        /// </summary>
        internal static string WrongEepromDataSize {
            get {
                return ResourceManager.GetString("WrongEepromDataSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification response must be {0} bytes long..
        /// </summary>
        internal static string WrongIdentificationResponseLength {
            get {
                return ResourceManager.GetString("WrongIdentificationResponseLength", resourceCulture);
            }
        }
    }
}
