//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibFloaderClient.Implementations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibFloaderClient.Implementations.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given EEPROM file contains data for addressess outside EEPROM. Check file correctness..
        /// </summary>
        internal static string AddressOutsideEeprom {
            get {
                return ResourceManager.GetString("AddressOutsideEeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up....
        /// </summary>
        internal static string BackingUp {
            get {
                return ResourceManager.GetString("BackingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups directory must be specified..
        /// </summary>
        internal static string BackupsDirectoryMustBeSpecified {
            get {
                return ResourceManager.GetString("BackupsDirectoryMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed.
        /// </summary>
        internal static string DownloadCompleted {
            get {
                return ResourceManager.GetString("DownloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded. Writting to file....
        /// </summary>
        internal static string DownloadedWritingInto {
            get {
                return ResourceManager.GetString("DownloadedWritingInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading EEPROM into {0}....
        /// </summary>
        internal static string DownloadingEepromInto {
            get {
                return ResourceManager.GetString("DownloadingEepromInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading FLASH into {0}....
        /// </summary>
        internal static string DownloadingFlashInto {
            get {
                return ResourceManager.GetString("DownloadingFlashInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEPROM backup file: {0}.
        /// </summary>
        internal static string EepromBackupFile {
            get {
                return ResourceManager.GetString("EepromBackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEPROM file to download into must be specified..
        /// </summary>
        internal static string EepromFileToDownloadMustBeSpecified {
            get {
                return ResourceManager.GetString("EepromFileToDownloadMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEPROM size: {0} bytes.
        /// </summary>
        internal static string EepromSize {
            get {
                return ResourceManager.GetString("EepromSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASH and EEPROM files must differ..
        /// </summary>
        internal static string FlashAndEepromMustDiffer {
            get {
                return ResourceManager.GetString("FlashAndEepromMustDiffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASH backup file: {0}.
        /// </summary>
        internal static string FlashBackupFile {
            get {
                return ResourceManager.GetString("FlashBackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASH file to download into must be specified..
        /// </summary>
        internal static string FlashFileToDownloadMustBeSpecified {
            get {
                return ResourceManager.GetString("FlashFileToDownloadMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least either FLASH or EEPROM files must be specified..
        /// </summary>
        internal static string FlashOrEepromMustBeSpecified {
            get {
                return ResourceManager.GetString("FlashOrEepromMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASH page size: {0} bytes.
        /// </summary>
        internal static string FlashPageSize {
            get {
                return ResourceManager.GetString("FlashPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASH page {0} verification failed..
        /// </summary>
        internal static string FlashPageVerificationFailed {
            get {
                return ResourceManager.GetString("FlashPageVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting version-specific data....
        /// </summary>
        internal static string GettingVersionSpecificData {
            get {
                return ResourceManager.GetString("GettingVersionSpecificData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to use not set up Device Independent Operations Provider.
        /// </summary>
        internal static string NotSetUpDIOProvider {
            get {
                return ResourceManager.GetString("NotSetUpDIOProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading EEPROM.
        /// </summary>
        internal static string ProgressOperationReadingEeprom {
            get {
                return ResourceManager.GetString("ProgressOperationReadingEeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading FLASH.
        /// </summary>
        internal static string ProgressOperationReadingFlash {
            get {
                return ResourceManager.GetString("ProgressOperationReadingFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing FLASH.
        /// </summary>
        internal static string ProgressOperationWritingFlash {
            get {
                return ResourceManager.GetString("ProgressOperationWritingFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading EEPROM....
        /// </summary>
        internal static string ReadingEeprom {
            get {
                return ResourceManager.GetString("ReadingEeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading FLASH (bootloader included)....
        /// </summary>
        internal static string ReadingFlash {
            get {
                return ResourceManager.GetString("ReadingFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting reboot....
        /// </summary>
        internal static string RequestingReboot {
            get {
                return ResourceManager.GetString("RequestingReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total FLASH pages: {0}.
        /// </summary>
        internal static string TotalFlashPages {
            get {
                return ResourceManager.GetString("TotalFlashPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get device data for VendorId={0}, ModelId={1}.
        /// </summary>
        internal static string UnableToGetDeviceData {
            get {
                return ResourceManager.GetString("UnableToGetDeviceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported version {0}..
        /// </summary>
        internal static string UnsupportedVersion {
            get {
                return ResourceManager.GetString("UnsupportedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given FLASH file contains data for addresses in non-writeable FLASH area. Check file correctness..
        /// </summary>
        internal static string UnwriteableFlashArea {
            get {
                return ResourceManager.GetString("UnwriteableFlashArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading EEPROM....
        /// </summary>
        internal static string UploadingEeprom {
            get {
                return ResourceManager.GetString("UploadingEeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading FLASH....
        /// </summary>
        internal static string UploadingFlash {
            get {
                return ResourceManager.GetString("UploadingFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version must be 1..
        /// </summary>
        internal static string VersionMustBeOne {
            get {
                return ResourceManager.GetString("VersionMustBeOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1 detected.
        /// </summary>
        internal static string VersionOneDetected {
            get {
                return ResourceManager.GetString("VersionOneDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writeable FLASH pages: {0}.
        /// </summary>
        internal static string WriteableFlashPages {
            get {
                return ResourceManager.GetString("WriteableFlashPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing EEPROM....
        /// </summary>
        internal static string WritingEeprom {
            get {
                return ResourceManager.GetString("WritingEeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing FLASH (except bootloader)....
        /// </summary>
        internal static string WritingFlash {
            get {
                return ResourceManager.GetString("WritingFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification response must be {0} bytes long..
        /// </summary>
        internal static string WrongIdentificationResponseLength {
            get {
                return ResourceManager.GetString("WrongIdentificationResponseLength", resourceCulture);
            }
        }
    }
}
