//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibIntelHex.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibIntelHex.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEX file string must not be null or empty..
        /// </summary>
        internal static string EmptyHexFileString {
            get {
                return ResourceManager.GetString("EmptyHexFileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path must not be empty..
        /// </summary>
        internal static string EmptyPath {
            get {
                return ResourceManager.GetString("EmptyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEX file must end with End of File record..
        /// </summary>
        internal static string EndsWithNonEof {
            get {
                return ResourceManager.GetString("EndsWithNonEof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEX file contains incorrect line. Line: {0}..
        /// </summary>
        internal static string IncorrectLine {
            get {
                return ResourceManager.GetString("IncorrectLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address must be in [0, {0}] range..
        /// </summary>
        internal static string InvalidAddress {
            get {
                return ResourceManager.GetString("InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEX file must contain one and only one End of File record..
        /// </summary>
        internal static string ManyEoFs {
            get {
                return ResourceManager.GetString("ManyEoFs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEX file contains not allowed record with type {0}..
        /// </summary>
        internal static string NotAllowedRecord {
            get {
                return ResourceManager.GetString("NotAllowedRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must never reach this place..
        /// </summary>
        internal static string ReachedUnreacheable {
            get {
                return ResourceManager.GetString("ReachedUnreacheable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEX file must contain at least two lines (DATA + EoF records)..
        /// </summary>
        internal static string TooSmallHexFile {
            get {
                return ResourceManager.GetString("TooSmallHexFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEX file contains line with a wrong checksum. Byte sequence with it: {0}..
        /// </summary>
        internal static string WrongChecksum {
            get {
                return ResourceManager.GetString("WrongChecksum", resourceCulture);
            }
        }
    }
}
